#!/usr/bin/env python3
"""Generate the problem index and README statistics from problem metadata."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

from repository import LANGUAGE_FILES, ROOT, implemented_languages, load_json, problem_directories


START_MARKER = "<!-- statistics:start -->"
END_MARKER = "<!-- statistics:end -->"


def render_index() -> str:
    rows = [
        "# Problem Index",
        "",
        "This file is generated by `python scripts/generate_index.py` from each problem's metadata.",
        "",
        "| ID | Problem | Difficulty | Category | Tags | Python | C++ | Go | Rust |",
        "| --- | --- | --- | --- | --- | :---: | :---: | :---: | :---: |",
    ]
    for problem in problem_directories():
        metadata = load_json(problem / "metadata.json")
        languages = set(implemented_languages(problem))
        cells = [
            str(metadata["id"]),
            f"[{metadata['title']}](../{problem.relative_to(ROOT).as_posix()}/)",
            str(metadata["difficulty"]),
            ", ".join(metadata["category"]),
            ", ".join(f"`{tag}`" for tag in metadata["tags"]),
            *("✓" if language in languages else "—" for language in LANGUAGE_FILES),
        ]
        rows.append("| " + " | ".join(cells) + " |")
    rows.append("")
    return "\n".join(rows)


def render_statistics() -> str:
    problem_count = 0
    language_counts: Counter[str] = Counter()
    for problem in problem_directories():
        problem_count += 1
        language_counts.update(implemented_languages(problem))
    fields = [f"Problems: {problem_count}"] + [
        f"{language.capitalize() if language != 'cpp' else 'C++'}: {language_counts[language]}"
        for language in LANGUAGE_FILES
    ]
    return START_MARKER + "\n" + " · ".join(fields) + "\n" + END_MARKER


def expected_files() -> dict[Path, str]:
    readme_path = ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    if START_MARKER not in readme or END_MARKER not in readme:
        raise ValueError("README.md is missing generated-statistics markers")
    prefix, remainder = readme.split(START_MARKER, maxsplit=1)
    _, suffix = remainder.split(END_MARKER, maxsplit=1)
    updated_readme = prefix + render_statistics() + suffix
    return {
        ROOT / "docs" / "problem-index.md": render_index(),
        readme_path: updated_readme,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    arguments = parser.parse_args()
    try:
        files = expected_files()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    stale: list[Path] = []
    for path, content in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not arguments.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if arguments.check and stale:
        for path in stale:
            print(f"STALE {path.relative_to(ROOT)}")
        return 1
    print("Generated repository index and statistics." if stale else "Generated files are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
